version: '3'

services:
###########
# Traefik #
###########
  traefik:
    image: traefik
    container_name: proxy_traefik
    restart: unless-stopped
    hostname: traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.%DOMAIN%
      - traefik.frontend.auth.basic=%VAR%
      - traefik.port=8080
      - traefik.docker.network=traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - %TRAEFIK%traefik.toml:/traefik.toml:ro
      - %TRAEFIK%letsencrypt/certs:/etc/traefik/acme:rw    
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: traefik_proxy
